version: '3.9'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app/app:ro
      - ./db_migration:/usr/src/db_migration:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
      - DB_PASSWORD=fastapi123
      - DB_USERNAME=postgres
      - DB_NAME=fastapi_fcc
      - SECRET_KEY=cef71093415dc5c7c06b5af5aff4cd49f6e36770b0db0b2f6ad07b998ef94cf2
      - ALGORITHM = "HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES = 15
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=fastapi123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fastapi_fcc
    
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    